In [1]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM
 
# 1. 데이터
x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6]])
y = array([4,5,6,7])
 
print('x shape : ', x.shape) # (4,3)
print('y shape : ', y.shape) # (4,)
#  x  y
# 123 4
# 234 5
# 345 6
# 456 7
 
print(x)
print('-------x reshape-----------')
x = x.reshape((x.shape[0], x.shape[1], 1)) # (4,3,1) reshape 전체 곱 수 같아야 4*3=4*3*1
print('x shape : ', x.shape)
print(x)
#  x        y
# [1][2][3] 4
# .....
 
# 2. 모델 구성
model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape=(3,1)))
# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)
model.add(Dense(5))
model.add(Dense(1))
 
model.summary()
 
# 3. 실행
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, batch_size=1)
 
x_input = array([6,7,8])
x_input = x_input.reshape((1,3,1))
 
yhat = model.predict(x_input)
print(yhat)


x shape :  (4, 3)
y shape :  (4,)
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
-------x reshape-----------
x shape :  (4, 3, 1)
[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 10)                480       
_________________________________________________________________
dense (Dense)                (None, 5)                 55        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6         
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
4/4 [==============================] - 1s 1ms/step - loss: 14.4065
Epoch 2/100
4/4 [==============================] - 0s 1ms/step - loss: 14.4940
Epoch 3/100
4/4 [=============

4/4 [==============================] - 0s 1ms/step - loss: 0.2861
Epoch 93/100
4/4 [==============================] - 0s 1000us/step - loss: 0.2799
Epoch 94/100
4/4 [==============================] - 0s 1000us/step - loss: 0.2743
Epoch 95/100
4/4 [==============================] - 0s 1ms/step - loss: 0.2948
Epoch 96/100
4/4 [==============================] - 0s 1ms/step - loss: 0.4094
Epoch 97/100
4/4 [==============================] - 0s 1ms/step - loss: 0.3988
Epoch 98/100
4/4 [==============================] - 0s 1000us/step - loss: 0.3824
Epoch 99/100
4/4 [==============================] - 0s 999us/step - loss: 0.3783
Epoch 100/100
4/4 [==============================] - 0s 1ms/step - loss: 0.2392
[[10.655611]]
